name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Flutter'ı GitHub Action içine kuruyoruz
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # Paketleri çekiyoruz
      - run: flutter pub get
      
      # Web build alıyoruz
      - run: flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DORTTEDORT }}' # Buradaki isim sendekine göre farklı olabilir, değiştirme
          channelId: live
          projectId: dorttedort # Buraya kendi firebase proje ID'ni yaz